### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xxnbyy** [Mosuan/FileScan#1]
Exception in thread Thread-1085 (most likely raised during interpreter shutdown):Exception in thread Thread-1064 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

Traceback (most recent call last):  File "/usr/lib/python2.7/threading.py", line 754, in run

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner  File "filescan.py", line 43, in _data
  File "filescan.py", line 61, in _check

  File "/usr/lib/python2.7/threading.py", line 754, in run  File "/root/github/FileScan/reque.py", line 38, in query

  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request  File "filescan.py", line 43, in _data
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 393, in __exit__
  File "filescan.py", line 61, in _check
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 702, in close
  File "/root/github/FileScan/reque.py", line 38, in query

  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close

  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 393, in __exit__

  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 702, in close  File "/usr/local/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 319, in close

  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 204, in clear<type 'exceptions.TypeError'>: 'NoneType' object is not callable
  File "/usr/local/lib/python2.7/dist-packages/urllib3/_collections.py", line 87, in clear

  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by Mosuan** [comment]
扫的什么站？可以在filescan.py time.sleep 修改为0.8试试

**Comment by xxnbyy** [comment]
改成0.1以后完成了扫描，还报了个其他错
Exception in thread Thread-1089 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "filescan.py", line 43, in _data
  File "filescan.py", line 61, in _check
  File "/root/github/FileScan/reque.py", line 38, in query
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'request'

**Comment by Mosuan** [comment]
提供下python版本和requests库的版本

**Comment by xxnbyy** [comment]
python 2.7.12  requests 2.18.4
